credentials:
  usernames:
    admin:
      email: ahmad.rizam@caam.gov.my
      name: System Administrator
      password: "$2b$12$sANqpB.RU43mr4D1s9CcsORpcUIQfZNql1/Sd/UHyR6L4aOUlayRy"
    Rizam:
      email: ahmad.rizam@caam.gov.my
      name: Ahmad Rizam bin Ghazali
      password: "$2b$12$10HGKDc/2B/c16GHYi4ekecqAk.Z./2GXa.LvEuoJLmRF2biTDBcC"
    Edie:
      email: edie@caam.gov.my
      name: Edie bin Amir
      password: "$2b$12$aWtgnbUrw0BtQWRYex3nfuPdioitoOqjGd6S6GkNpN.FJRjuVu6Si"
    Azhan:
      email: azhan@caam.gov.my
      name: Mohd Azhan Bin Md Januri
      password: "$2b$12$kHOzoDvrwzVzMq5Ol/7MCu6cblMZfmjy2pKjYmps9uvSKl0NaNpYa"
    Farizza:
      email: farizza@caam.gov.my
      name: Farizza Rowenna Bt Abd Samad
      password: "$2b$12$3WbR1G2U8qGrwgKsW9BPyeEbNF2yoRbjcMRfJQuwoolXN6XfJqyTG"
    Rithauddin:
      email: rithauddin@caam.gov.my
      name: Ahmad Rithauddin Bin Hamiyuddin
      password: "$2b$12$OAvOw.93uM9lWfK0gCUBmuxo5cVqOf3OgWun4ArnG1xkbjUJNIolm"
    Zawawi:
      email: chezawawi@caam.gov.my
      name: Che Zawawi Bin Che Musa
      password: "$2b$12$foL0oAgVBRVN6/ARWvGtq.U6NfMGznYApcPgGn8duttACWVBvHjVe"
    Rizal:
      email: rizal@caam.gov.my
      name: Mohd Rizal Bin Mohamad Salleh
      password: "$2b$12$ca3VpZ730.kOscVcVCKVsO3iGzaEAeWe9V7cee.CiweMRVc.IBUtu"
    Pudin:
      email: -
      name: Mohd Afifuddin Hilmi Bin Zuraki
      password: "$2b$12$EGmw2tp1WCNX1GvqhtLcTudsQa9j5JGa4E9VognIrtMRfaUGYkS3W"
    Siwa:
      email: siwa@caam.gov.my
      name: Siwa A/L Mathaban
      password: "$2b$12$.5aGRpbk2vNNJ.eSIQe0xOtVMxaayKGX45LWOGfQCY11Na8zNvZW6"  
      
cookie:
  expiry_days: 14
  key: a_very_secret_random_key_change_this_in_production
  name: atc_rag_auth_cookie